import Head from "next/head";
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
  Grid,
} from "@/components/sharedstyles";
import Cards from "@/components/cards";
import { FormEvent, useState } from "react";

export default function Home() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  
  function handleSubmit(event: FormEvent<HTMLFormElement>): void {
    throw new Error("Function not implemented.");
  }

  return (
    <Grid>
      <Head>
        <title>Prestalana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>
          Welcome to <a href="https://nextjs.org">Prestalana!</a>
        </Title>

      <form onSubmit={handleSubmit}>
      <p>Login</p>
      <input
        name="email"
        type="email"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
      />
      <input
        name="password"
        type="password"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
      />
      <input type="submit" value="Submit" />
      
    </form>

        <Cards />
      </Main>
    </Grid>
  );
}
